apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jis9ys23j-nodejs
  janus-idp.io/tekton: jis9ys23j-nodejs
  backstage.io/kubernetes-id: jis9ys23j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jis9ys23j-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
