apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jis9ys23j-nodejs-gitops
  description: This is GitOps manifest for jis9ys23j-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=jis9ys23j-nodejs
    backstage.io/kubernetes-id: jis9ys23j-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jis9ys23j-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jis9ys23j-nodejs
